/**
 * National Pokédex number → species display name.
 *
 * `data/pokedex.json` is generated by `scripts/refresh-pokedex.ts` (source: PokéAPI). It gives
 * every `pokemon` graph node a canonical species name ("Charizard") independent of the card name
 * ("Charizard ex", "Dark Charizard", "Charizard VMAX"...).
 */
import pokedex from '../data/pokedex.json'

const table: Record<string, string> = pokedex as Record<string, string>

export function speciesName(dexId: number): string | null {
  return table[String(dexId)] ?? null
}

const PREFIXES = [
  "Team Rocket's ",
  'Dark ',
  'Light ',
  'Shining ',
  'Radiant ',
  'Alolan ',
  'Galarian ',
  'Hisuian ',
  'Paldean ',
  'M ',
  'Mega ',
]

const SUFFIXES = [
  ' ex',
  ' EX',
  '-EX',
  ' GX',
  '-GX',
  ' V',
  ' VMAX',
  ' VSTAR',
  ' V-UNION',
  ' LV.X',
  ' BREAK',
  ' Prime',
  ' LEGEND',
  ' Star',
  ' δ',
  ' ◇',
  ' ☆',
]

/**
 * Best-effort species name from a card name when the Pokédex table has no entry.
 * Strips owner prefixes ("Brock's "), form prefixes and mechanic suffixes.
 */
export function baseSpeciesName(cardName: string): string {
  let name = cardName.trim()
  const owner = /^[A-Z][\w.]*'s\s+/.exec(name)
  if (owner) name = name.slice(owner[0].length)
  for (const prefix of PREFIXES) {
    if (name.startsWith(prefix)) {
      name = name.slice(prefix.length)
      break
    }
  }
  let changed = true
  while (changed) {
    changed = false
    for (const suffix of SUFFIXES) {
      if (name.endsWith(suffix) && name.length > suffix.length) {
        name = name.slice(0, -suffix.length)
        changed = true
      }
    }
  }
  return name.trim()
}

const HYPHENATED = new Set([
  'ho-oh',
  'porygon-z',
  'jangmo-o',
  'hakamo-o',
  'kommo-o',
  'wo-chien',
  'chien-pao',
  'ting-lu',
  'chi-yu',
])

const SPECIAL: Record<string, string> = {
  'nidoran-f': 'Nidoran♀',
  'nidoran-m': 'Nidoran♂',
  farfetchd: "Farfetch'd",
  sirfetchd: "Sirfetch'd",
  'mr-mime': 'Mr. Mime',
  'mr-rime': 'Mr. Rime',
  'mime-jr': 'Mime Jr.',
  'type-null': 'Type: Null',
  flabebe: 'Flabébé',
  'jangmo-o': 'Jangmo-o',
  'hakamo-o': 'Hakamo-o',
  'kommo-o': 'Kommo-o',
}

/** PokéAPI slug ("great-tusk", "ho-oh", "mr-mime") → display name. */
export function prettifySpeciesSlug(slug: string): string {
  const special = SPECIAL[slug]
  if (special) return special
  const parts = slug.split('-').map((p) => p.charAt(0).toUpperCase() + p.slice(1))
  return HYPHENATED.has(slug) ? parts.join('-') : parts.join(' ')
}
